from typing import Protocol, AsyncIterator


class AudioCapturePort(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def read_frames(self) -> AsyncIterator[bytes]: ...

    @property
    def sample_rate(self) -> int: ...

    @property
    def frame_size(self) -> int: ...


class AudioPlaybackPort(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def play_chunk(self, audio_data: bytes) -> None: ...
    async def drain(self) -> None: ...
    async def cancel(self) -> None: ...
